spring.application.name=MyHotel
spring.datasource.url=jdbc:postgresql://localhost:5432/myhotel_test
spring.datasource.username=beny_database
spring.datasource.password=mydatabasepassword
spring.security.name=Beny
spring.security.password=123456
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

